### PR TITLE
deploy mainnet chains

### PR DESCRIPTION
**Pull request by gravityblast**

### CODE REVIEW

**Comment by vacekj** [comment]
Should there be a arbitrum.json file created, as there is for optimism and others?

**Comment by gravityblast** [comment]
@vacekj thank you man, I added them!

**Review by vacekj — APPROVED** [review]

**Comment by michellema1208** [comment]
@vacekj @gravityblast was this merged?

**Comment by vacekj** [comment]
@michellema1208 it is now 😄

**Pull request merged**
